### ISSUE TITLE
Improve G2 deserialization performance in arkworks

### ISSUE THREAD

**Issue by ggkitsas** [anoma/ferveo#58]

**Comment by simonmasson** [comment]
The deserialization in arkworks is currently very slow because of the subgroup check:
```
test bls12_381::g1::deser           ... bench:     190,636 ns/iter (+/- 3,634)
test bls12_381::g1::deser_unchecked ... bench:         116 ns/iter (+/- 3)
test bls12_381::g1::ser             ... bench:         100 ns/iter (+/- 1)
test bls12_381::g1::ser_unchecked   ... bench:          73 ns/iter (+/- 1)
test bls12_381::g2::deser           ... bench:     630,359 ns/iter (+/- 4,483)
test bls12_381::g2::deser_unchecked ... bench:         241 ns/iter (+/- 2)
test bls12_381::g2::ser             ... bench:         144 ns/iter (+/- 1)
test bls12_381::g2::ser_unchecked   ... bench:         145 ns/iter (+/- 2)
```
Using the technique of eprint 2019/814 would lead to a more efficient subgroup check and hence a more efficient deserialization.

**Comment by simonmasson** [comment]
Benchmarks can be reproducible in the `heliaxdev/curves` repository, branch `simon/fast-subgroup-checks`.
```
cd /tmp
git clone git@github.com:heliaxdev/curves.git
cd curves/curve-benches/
git checkout simon/fast-subgroup-checks
cargo bench -- bls12_381 --exact
```
Next step is to benchmark the functions of Ferveo. It will be done in the branch `simon/fast-subgroup-checks` of Ferveo.

**Comment by simonmasson** [comment]
The subgroup check has been added to `arkworks-rs/{algebra, curves}`. Maybe the square root algorithm can be computed faster (?).
